org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.unsafe.configuration-cache=true

#Android
android.useAndroidX=true

#Kotlin
kotlin.native.ignoreDisabledTargets=true
kotlin.code.style=official

#iOS
xcodeproj=./app/ios

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
