[versions]
# Android specific
compileSdk = "37"
minSdk = "23" # Android 6.0
targetSdk = "37"

# iOS specific
ios-minTarget = "16.0"
spm-googleMaps = "10.13.0"

agp = "9.3.0"
buildkonfig = "0.22.0"
decompose = "3.5.0"
compose = "1.11.1"
essenty = "2.5.0"
firebase-bom = "34.16.0"
gitlive = "2.5.0"
koin = "4.2.2"
kotlinx-serialization = "1.11.0"
kotlin = "2.4.10"
mvikotlin = "4.4.0"

[libraries]
androidx-activity-compose = "androidx.activity:activity-compose:1.13.0"
androidx-annotation = "androidx.annotation:annotation:1.10.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.7.1"
androidx-browser = "androidx.browser:browser:1.10.0"
androidx-core = "androidx.core:core-ktx:1.19.0"
androidx-core-splashscreen = "androidx.core:core-splashscreen:1.2.0"
androidx-datastore = "androidx.datastore:datastore-preferences:1.2.1"
androidx-datastore-core = "androidx.datastore:datastore-preferences-core:1.2.1"
androidx-media3-exoplayer = "androidx.media3:media3-exoplayer:1.10.1"

compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }

compose-material3 = "org.jetbrains.compose.material3:material3:1.9.0"
compose-material3-adaptive = "org.jetbrains.compose.material3.adaptive:adaptive:1.3.0-beta02"

decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }

desugar-jdk = "com.android.tools:desugar_jdk_libs:2.1.5"
dev-gitlive-firebase-analytics = { module = "dev.gitlive:firebase-analytics", version.ref = "gitlive" }
dev-gitlive-firebase-crashlytics = { module = "dev.gitlive:firebase-crashlytics", version.ref = "gitlive" }
dev-gitlive-firebase-database = { module = "dev.gitlive:firebase-database", version.ref = "gitlive" }
dev-gitlive-firebase-firestore = { module = "dev.gitlive:firebase-firestore", version.ref = "gitlive" }

essenty-backhandler = { module = "com.arkivanov.essenty:back-handler", version.ref = "essenty" }
essenty-lifecycle = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }
essenty-lifecycle-coroutines = { module = "com.arkivanov.essenty:lifecycle-coroutines", version.ref = "essenty" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-database = { module = "com.google.firebase:firebase-database" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }

google-app-update = "com.google.android.play:app-update-ktx:2.1.0"
google-maps = "com.google.maps.android:maps-ktx:6.2.0"
google-maps-utils = "com.google.maps.android:android-maps-utils:5.0.0"

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

kotlin-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0"
kotlin-coroutines-playservices = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.11.0"
kotlin-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.8.0"
kotlin-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

mvikotlin = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mvikotlin" }
mvikotlin-main = { module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mvikotlin" }
mvikotlin-extensions = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mvikotlin" }

play-services-location = "com.google.android.gms:play-services-location:21.4.0"
play-services-maps = "com.google.android.gms:play-services-maps:20.0.0"

# Dependencies for build-logic module
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
compose-compiler-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
buildkonfig-compiler = { module = "com.codingfeline.buildkonfig:buildkonfig-compiler", version.ref = "buildkonfig" }
buildkonfig-gradle = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "buildkonfig" }

# 3rd party tools
compose-rules = "io.nlopez.compose.rules:ktlint:0.6.3"
ktlint = "com.pinterest.ktlint:ktlint-cli:1.8.0"

[bundles]
mvikotlin = ["mvikotlin", "mvikotlin-main", "mvikotlin-extensions"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.7" }
google-services = { id = "com.google.gms.google-services", version = "4.5.0" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version = "2.0.1" }
spotless = { id = "com.diffplug.spotless", version = "8.8.0" }

# Project conventional plugins
grodnoroads-application = { id = "grodnoroads.application" }
grodnoroads-multiplatform-library = { id = "grodnoroads.multiplatform.library" }
grodnoroads-kmp-compose = { id = "grodnoroads.kmp.compose" }
