[versions]
compileSdk = "34"
minSdk = "23"
targetSdk = "33"

agp = "8.1.2"
accompanist = "0.32.0"
compose-compiler = "1.5.3"
decompose = "2.0.1"
koin-android = "3.4.3"
koin-compose = "3.4.6"
kotlin = "1.9.10"
mvikotlin = "3.2.1"

[libraries]
# Dependencies of the included build-logic
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

androidx-compose-bom = "androidx.compose:compose-bom:2023.09.00"
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
# https://issuetracker.google.com/issues/299503076
androidx-compose-material3 = "androidx.compose.material3:material3:1.2.0-alpha06"
androidx-compose-material3-window = "androidx.compose.material3:material3-window-size-class:1.1.1"
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

androidx-activity-compose = "androidx.activity:activity-compose:1.7.2"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-browser = "androidx.browser:browser:1.6.0"
androidx-core = "androidx.core:core-ktx:1.12.0"
androidx-core-splashscreen = "androidx.core:core-splashscreen:1.0.1"
androidx-datastore = "androidx.datastore:datastore-preferences:1.0.0"
androidx-media = "androidx.media:media:1.6.0"

balloon-compose = "com.github.skydoves:balloon-compose:1.5.5-SNAPSHOT"

coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
coroutines-playservices = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.7.3"

decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-compose-jetpack = { module = "com.arkivanov.decompose:extensions-compose-jetpack", version.ref = "decompose" }

firebase-bom = "com.google.firebase:firebase-bom:32.2.3"
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-database = { module = "com.google.firebase:firebase-database-ktx" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore-ktx" }

google-maps = "com.google.maps.android:maps-ktx:3.4.0"
google-maps-utils = "com.google.maps.android:android-maps-utils:3.5.3"
google-material = "com.google.android.material:material:1.9.0"

immutable-collections = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-android" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-compose" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

mvikotlin = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mvikotlin" }
mvikotlin-main = { module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mvikotlin" }
mvikotlin-extensions = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mvikotlin" }

play-services-location = "com.google.android.gms:play-services-location:21.0.1"
play-services-maps = "com.google.android.gms:play-services-maps:18.1.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "2.9.9" }
google-services = { id = "com.google.gms.google-services", version = "4.3.15" }
gradle-dependency-check = { id = "com.github.ben-manes.versions", version = "0.48.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version = "2.0.1" }