source 'https://cdn.cocoapods.org'

target 'grodno-roads-ios' do
   use_frameworks!
   platform :ios, '15.0'

   pod 'GoogleMaps', '~> 8.4.0'
   pod 'BottomSheet', :git => 'https://github.com/joomcode/BottomSheet'
   pod 'FirebaseCore', '~> 10.23.0'
   pod 'FirebaseDatabase', '~> 10.25.0'
   pod 'FirebaseCrashlytics', '~> 10.25.0'
   pod 'FirebaseFirestore', '~> 10.25.0'
   pod 'root', :path => '../../kmp/features/root'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end