name: verify apps

on:
  workflow_dispatch:

  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Make secrets.properties
        run: echo ${{ secrets.SECRETS_PROPERTIES }} | base64 --decode > secrets.properties

      - name: Spotless check
        run: ./gradlew spotlessCheck
