name: Verify Android/iOS apps

on:
  workflow_dispatch:

  pull_request:
    branches: [ "develop" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-
            gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Copy google-services.json
        run: echo ${{ secrets.GOOGLE_JSON }} | base64 --decode > app/android/google-services.json

      - name: Make secrets.properties
        run: echo ${{ secrets.SECRETS_PROPERTIES }} | base64 --decode > secrets.properties

      - name: Spotless check
        run: ./gradlew spotlessCheck

      - name: Run Android tests
        run: ./gradlew testDebugUnitTest

      - name: Build Android app
        run: ./gradlew app:android:assembleDebug

      - name: Build UI Demo app
        run: ./gradlew app:ui-demo:assembleDebug

  ios-test:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-
            gradle-

      - name: Cache Pods
        uses: actions/cache@v4
        with:
          path: app/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('app/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Make secrets.properties
        run: echo ${{ secrets.SECRETS_PROPERTIES }} | base64 --decode > secrets.properties

      - name: Copy GoogleService-Info.plist
        run: echo ${{ secrets.IOS_GOOGLE_SERVICES_INFO_PLIST }} | base64 --decode > app/ios/grodno-roads-ios/Resources/GoogleService-Info.plist

      - name: Generate Kotlin Framework
        run: ./gradlew :kmp:features:root:generateDummyFramework

      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: app/ios/Podfile.lock

      - name: Install CocoaPods
        run: |
          cd app/ios
          pod install

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.0.0

      - name: Build app
        run: xcodebuild -workspace app/ios/grodno-roads-ios.xcworkspace -scheme grodno-roads-ios -sdk iphonesimulator build
