name: verify apps

on:
  workflow_dispatch:
  
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        cache: gradle
        
    - name: Build with Gradle
      run: ./gradlew build
