name: verify apps

on:
  workflow_dispatch:

  pull_request:
    branches: [ "develop" ]

jobs:
  android-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Copy google-services.json
        run: echo ${{ secrets.GOOGLE_JSON }} | base64 --decode > app/android/google-services.json

      - name: Make secrets.properties
        run: echo ${{ secrets.SECRETS_PROPERTIES }} | base64 --decode > secrets.properties

      - name: Spotless check
        run: ./gradlew spotlessCheck

      - name: Run Android tests
        run: ./gradlew testDebugUnitTest

      - name: Build Android app
        run: ./gradlew app:android:assembleDebug

      - name: Build UI Demo app
        run: ./gradlew app:ui-demo:assembleDebug

#  ios-test:
#    runs-on: macos-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: 17
#          cache: gradle
#
#      - name: Make secrets.properties
#        run: echo ${{ secrets.SECRETS_PROPERTIES }} | base64 --decode > secrets.properties
#
#      - name: Run iOS tests
#        run: ./gradlew iosSimulatorArm64Test
